name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      file_1 :
        required: true
        type: string
      file_2 :
        type: string
        required: true

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send diff
      run: diff (cat ${{ inputs.file_1 }}) (cat ${{ inputs.file_2 }})
