name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backups_dir:
        type: string
        required: true

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send diff
      run: |
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'

        $last_backup_path = (gci ${{ inputs.backups_dir }} | sort LastWriteTime | select -last 1).FullName
        $last_backup = [System.IO.Compression.ZipFile]::OpenRead($last_backup_path)

        foreach ($entry in $last_backup.Entries) {
          if ($entry.FullName -like "*/file.txt") {
            $stream = $entry.Open()
            $reader = New-Object System.IO.StreamReader($stream)
            $content = $reader.ReadToEnd()
            $reader.Close()
            $stream.Close()

            echo "Content of $($entry.FullName):"
            echo $content

            $new_file_content = Get-Content ${{ inputs.new_file }}

            $diff = Compare-Object -ReferenceObject $new_file_content -DifferenceObject $content.Split("`n")

            if ($diff) {
              echo "Differences found between the new file and the backup file:"
              echo $diff | Out-File -FilePath ./diff.log
              cat ./diff.log
            } else {
              echo "No differences found."
            }
          } else {
            echo "$entry is not file.txt"
            continue
            }
          }
