name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backups_dir:
        required: true
        type: string

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract file contents
      run: |
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'

        $lastBackupPath = (Get-ChildItem "${{ inputs.backups_dir }}" | Sort-Object LastWriteTime | Select-Object -Last 1).FullName
        $zip = [System.IO.Compression.ZipFile]::OpenRead($lastBackupPath)
        
        $backupContent = ""
        foreach ($entry in $zip.Entries) {
          if ($entry.FullName -like "*/file.txt") {
            $reader = New-Object System.IO.StreamReader($entry.Open())
            $backupContent = $reader.ReadToEnd()
            $reader.Close()
            break
          }
        }
        $zip.Dispose()

        $newFileContent = Get-Content "${{ inputs.new_file }}" -Raw

        # Save both contents to environment variables
        $backupEncoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($backupContent))
        $newFileEncoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($newFileContent))

        echo "BACKUP_CONTENT=$backupEncoded" >> $env:GITHUB_ENV
        echo "NEW_FILE_CONTENT=$newFileEncoded" >> $env:GITHUB_ENV

    - name: Run custom diff action
      uses: Sousfiane/diff@v1
      with:
        old_file: ${{ env.BACKUP_CONTENT }}
        new_file: ${{ env.NEW_FILE_CONTENT }}

    - name: Print Output
      id: output
      run: echo "${{ steps.run-action.outputs.time }}"

