name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backup_archive:
        type: string
        required: true

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send diff
      run: |
        Expand-Archive -Path ${{ inputs.backup_archive }} -DestinationPath ./backup_unzipped
        diff (cat ${{ inputs.new_file}}) (cat ./backup_unzipped/backup/file.txt)
