name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backups_dir:
        type: string
        required: true

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send diff
      run: |
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
        $last_backup_path = (gci ${{ inputs.backups_dir }} | sort LastWriteTime | select -last 1).FullName
        $last_backup = [System.IO.Compression.ZipFile]::OpenRead($last_backup_path)
        echo "The last backup is $last_backup"
        foreach ($entry in $last_backup.Entries){
          if ($entry -like "*/file.txt") {
            diff (cat ${{ inputs.new_file}}) (cat $entry)
          }else {
            echo "$entry is not file.txt"
            continue
          }
        }
