name: 010-diff-workflow

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backups_dir:
        type: string
        required: true

jobs:
  diff:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Send diff
      run: |
        cp ((gci ${{ inputs.backups_dir }} | sort LastWriteTime | select -last 1).FullName) ./last_backup_archive
        Expand-Archive -Path ./last_backup_archive -DestinationPath ./backup_unzipped
        diff (cat ${{ inputs.new_file}}) (cat ./backup_unzipped/backup/file.txt)
