name: 020-diff-pipeline

on:
  workflow_dispatch:
    inputs:
      file_1 :
        required: true
        type: string
      file_2 :
        type: string
        required: true

jobs:
  call_backup_workflow:
    runs-on: windows-latest

    uses: ./.github/workflows/010-diff-workflow.yml@main
    with:
      file_1:
      file_2:
