name: 020-diff-pipeline

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backup_archive:
        type: string
        required: true

jobs:
  call_backup_workflow:
    uses: ./.github/workflows/010-diff-workflow.yml
    with:
      new_file: ${{ inputs.new_file }}
      backup_archive: ${{ inputs.backup_archive }}
