name: 020-diff-pipeline

on:
  workflow_call:
    inputs:
      new_file:
        required: true
        type: string
      backups_dir:
        type: string
        required: true

jobs:
  call_backup_workflow:
    uses: ./.github/workflows/010-diff-workflow.yml
    with:
      new_file: ${{ inputs.new_file }}
      backups_dir: ${{ inputs.backups_dir }}
