name: 020-diff-pipeline

on:
  workflow_call:
    inputs:
      file_1 :
        required: true
        type: string
      file_2 :
        type: string
        required: true

jobs:
  call_backup_workflow:
    uses: ./.github/workflows/010-diff-workflow.yml
    with:
      file_1: ${{ inputs.file_1 }}
      file_2: ${{ inputs.file_2 }}
